swagger: "2.0"
info:
  version: "0.0.1"
  title: "526 Soccer Database Application"
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /getPlayers:
    x-swagger-router-controller: player_controller
    get:
      description: Retrieves all players in the database and returns them as JSON data.
      operationId: getAllPlayers
      responses:
        "200": #Add player list as return value.
          description: Success
        "404":
          description: Data not found
          schema:
            $ref: "#/definitions/NotFoundErrorResponse"
  /getPlayers/{playerName}:
    x-swagger-router-controller: player_controller
    get:
      description: Retrieves all players in the database whose names contain the provided search text and returns them as JSON data.
      operationId: getPlayer
      parameters:
        - in: path
          name: playerName
          required: true
          type: string
          description: The text to search players by
      responses:
        "200": #Add player list as return value.
          description: Success
        "404":
          description: Data not found
          schema:
            $ref: "#/definitions/NotFoundErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /getTeams:
    x-swagger-router-controller: team_controller
    get:
      description: Retrieves all teams in the database and returns them as JSON data.
      operationId: getAllTeams
      responses:
        "200": #Add team list as return value.
          description: Success
        "404":
          description: Data not found
          schema:
            $ref: "#/definitions/NotFoundErrorResponse"
  /getTeams/{teamName}:
    x-swagger-router-controller: team_controller
    get:
      description: Retrieves all teams in the database whose names contain the provided search text and returns them as JSON data.
      operationId: getTeam
      parameters:
        - in: path
          name: teamName
          required: true
          type: string
          description: The text to search team by
      responses:
        "200": #Add player list as return value.
          description: Success
        "404":
          description: Data not found
          schema:
            $ref: "#/definitions/NotFoundErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  NotFoundErrorResponse:
    required:
      - message
      - errorCode
    properties:
      message:
        type: string
      errorCode:
        type: integer
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
